import React, { useEffect } from "react";
import { GoogleSpreadsheet } from "google-spreadsheet";

const _test = () => {
  useEffect(() => {
    const a = async () => {
      // Initialize the sheet - doc ID is the long id in the sheets URL
      const doc = new GoogleSpreadsheet(
        "1qk78PF2aOOnKFivW1kvvWDXbq6xRxQSaeu5jg7-EB4k"
      );

      // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
      await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: "ecl-awards@resonant-hawk-269217.iam.gserviceaccount.com",
        private_key:
          "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmv0twEFTOqSzg\nQPDJMsHrbOSS/AVHLw+UO4cRjLje4hqYV5Wd1rrksa24Uj5KguDZLDX9+xIiuPFP\nHdAtRnKddI5q42nE5IqYa1BmsUqi5LYIF1dZxgr0mdMKTvtidr9Wjw1D9dBFsf5G\nouAgcyEQswV3NSLq9k/mHRGx/6/X/FT4Muta56Gx9tL5+U1pu0vYbBB1uPyrJjyb\nKUWF4+E+6FriD45BWCj9WeCZ+pPJa0pXQdLrTOTelvnWzotkXz6Q6j/NWgMh47Cs\n1s40RpPAUWrrL9KHzIdwVr1azxObqfk8k9xtUZ25SbWqciOv5Bak2E4hQ2Y6Sn10\ncSNGi54nAgMBAAECggEABv7gjdeJj1AGq3PeBjrkatmbL1V2bTmauDfVH1XdjbBD\nuF94TfJrzdtsc96zcVHTWBkkPL8TUDSdHxobmUKq3VM+BFr9HX8PF3ztFxnaDUJ2\nJpnAFuqZnBB2C6krn8JmnZ2Ly22dKsdgaRs9Nu9NlFNGZ+1pRR1HVdqjWunkuTVy\nCEoWZMcyk0E1N0IK6O0d/ht/aJkUqia/Pg2x+BRDsW/BP1I3PTHURlelTsN6RSfd\ntMrHmvpX/5/WFjahnW9cFGfTG+GoYZcAOAG7VZxzfmRdE2tgibr3ylSF0HqLqfF6\n3k1jhN1I3zJzJ3nSzOfyF8rjvut8tZwrG+ei4kOQJQKBgQDaXb5t5+4PPdg3d2g2\nIeS02AONZmn0LqkC/u1Cnq6nlaN5xpS/OcTkHUcf3mW10pNzp+UzbvCrhvrR0u80\n6JnNGtzKLXy87wnXyGqnpJUJqHzs3FUqGXG4TNVZjhCg3qyCCY6nzCy5l0YVMZjH\n4PkzOZ+/q7WO4TK/Y8GOMoRH4wKBgQDDfCMkru2HPREENoUoUn8fYjgMPstyg7aW\n4Fk+vvatj88UrpfyI7vp2K23hgSX417zcMtuTQUH277Rvv+1coJneVH8SSf4AvU9\nH0VuvAhmNvD8hMeTJVuNVItK2MSUfanTZXX5zuzFjHP5rSGVp0b426Z3erMqWDg3\neJJF5jl77QKBgC/A6HAolEsI/0vB9SxBZT6XLs+xYeJggd2B2mkDQrarZsCuyMC4\n5XHtZSx2+k806cIVKW6CCGe6cQeJ1X4AkAHmqfoc0HaQ39osngZjW6RtEETMOmOm\nhNQFGXMoOkKz743QgT34zJ8Zkd34pqyvak/lfiXwaxf/75UjP6TVL1B5AoGAHAI3\nTtQ5eD0JqR7eqU5YpHiAK1D7+WZhzPBMGS9nTKrkMsRpROpVzEWdbkQneFO9kQfC\nPgWPCPc1Ofwxyx+jC4xYcNtSfLh/xsgqPJl4YpzQnn2v0qdxnKhWZNz2HYh7wqww\n4SAC0LM1Err5quWSx6lBCrFr5k9JjrkZzCYWamkCgYEAmt7uRGwfP5kDHHQCDOL7\n3dgeLtxgL6Ca4sEwaDH2e0WIBHjeD5WDeqpTIzP/Xb09KQV3zYLU3MSKGnd41o9g\n6IUUVWXVgpwk1v7nET5ilOvfdDxPow112K3yVxJXPeuXSPVuRvMRNASpsyCnN+Fu\nTA0siwyW3IJ8vIHPFl0o4f4=",
      });

      await doc.loadInfo(); // loads document properties and worksheets
      console.log(doc.title);
      await doc.updateProperties({ title: "renamed doc" });

      const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
      console.log(sheet.title);
      console.log(sheet.rowCount);

      // adding / removing sheets
      const newSheet = await doc.addSheet({ title: "hot new sheet!" });
      await newSheet.delete();
    };
    a();
  });
  return <div>_test</div>;
};

export default _test;
